### ISSUE TITLE
Search - add do_not_email, do_not_phone, do_not_sms and do_not_mail to search blade and scope

### ISSUE THREAD

**Issue by arborrow** [arborrow/montserrat#170]
I made an initial commit - but it is only a partial solution. Should be reworked to handle when we want just a 0 or a 1 or either (in otherwords when to ignore the search criteria for these fields).

**Comment by 0729singhrahul** [comment]
Updated the code with a dropdown menu with the following options: Ignore, Yes, No for each of the mentioned

**Comment by arborrow** [comment]
fixed
