### ISSUE TITLE
Send retreat confirmation emails automagically

### ISSUE THREAD

**Issue by arborrow** [arborrow/montserrat#171]
On the event table, there are fields like confirm_text that we can use to hold html of the message let's see if we can make this more dynamic by using those fields for the pre-retreat and post-retreat emails

We want to move the buttons off of the contact show blade to the retreat show blade in the registration section of the page and then add a button that will process all of the retreatants at once. Also, once the confirmation email has been sent, we should no longer show the button 

GS: route for confirmation tokens has been created. participants can now confirm their attendance from registration email. participant gets redirect to generic thank you page in squarespace

GS: @arborrow based on previous discussion. Emails will currently not be sent automatically. A route has been created to send the registration email. A button to has been added to person show view to access this route. Still need to implement confirmation route.

AB: reply to should be registration@montserratretreat.org - subject for this current retreat was: Preparing for your Upcoming Retreat #201807 starting on Thursday, February 1st 

GS: @anthonyborrow who should the reply to be set? For subject, should it just be something simple. "Montserrat Jesuit Retreat House Registration"?

AB: Sample text for email:

Dear [first name],

We are praying for you as your upcoming retreat approaches on [date]. You will find a beautiful campus, made holy by the thousands who have prayed here, that is both hospitable and restorative.

Check-in for your retreat is between 4:00 – 6:00 p.m. on [day,date]. Dinner will be served from 6:00 – 7:15 p.m. When you arrive, please come to Campion Hall to receive your room key and retreat packet. Below are some possible suggestions regarding what to bring. Some frequently asked questions can be found on our FAQs webpage but feel free to call or email should you need more information.

We look forward to welcoming and accompanying you during the retreat.

In the Lord,
Fr. Anthony Borrow, S.J.
Director

P.S. If you have a moment, it is helpful to confirm your attendance by clicking here [link]. If your plans have changed and you need to reschedule your retreat please call us at 940-321-6020 or send an email to registration@montserratretreat.org.

What is provided:
• All meals, snacks and beverages
• Bed linens, pillows, towels, and washcloths
• Each room has a private bath and individually controlled cooling/heating units

What to bring:
• Personal medicines, toiletries and hairdryer
• Comfortable, casual clothes and walking shoes
• A pen, journal or notebook
• A water bottle for taking beverages out of the dining hall
• All buildings are air-conditioned in the summer, so a light jacket or sweater may be helpful

**Comment by arborrow** [comment]
I would like to be able to customize the event's confirm_text and we can use the confirm_email_text field in the event table to store that text so that it is customizable per event. After sending the confirmation we should add a touchpoint but I would also like to be able to see the date/time the email was sent and to whom it was sent and possibly be able to send the confirmation email to an individual user (so they register late - after the confirm email has been sent to the others. Let's give some thought how we can ensure that we know what in fact has happened and how to relay that through the interface.

**Comment by arborrow** [comment]
@djaw if you don't mind, this is the next issue I would like you to tackle when you have time

**Comment by Djaw** [comment]
**Important**: Restart supervisor workers, to ensure use of updated email templates.
1. sudo supervisorctl 
2. restart all

**Comment by arborrow** [comment]
@Djaw - You may want to take a look at: https://github.com/laravel/framework/issues/2554 - it appears that the links being generated for the email confirmation is localhost rather than polanco and as a result are not functional for the end users. 

FYI, I will be working on creating some waitlist functionality into polanco in another issue but we will want to ensure that the confirmation email goes only to folks who have a status_id of 1 (registered) in the participant table. Initially Polanco will handle status of registered, attended, canceled, waitlist, rejected. 

Let me know if you have any questions. Peace - Anthony

**Comment by Djaw** [comment]
Got it, I will have a look at it.

**Comment by arborrow** [comment]
While you are looking at it - let's make sure to add a check that we only send to people if the registration is active (i.e. in the participant table, the status_id field should be 1 (registered). This will automatically exclude canceled or waitlisted folks (which I am working on in #210)
