### ISSUE TITLE
Fix migration related errors

### ISSUE THREAD

**Issue by AtaGowani** [arborrow/montserrat#219]
## Description
There are several errors that show up once `php artisan migrate` in called under the homestead vagrant box. Below are the errors and some details.
### Errors
**Following migrations have multiple files defined under `database/migrations`**
* `CreateFailedJobsTable`
* `CreateJobsTable`
* `CreatePasswordResetsTable`
* `CreateUsersTable`

**`CreateNoteTable` is throwing an error**
* Seems like line 20 `$table->text('note', 65535)->nullable()->index('idx_note');` isn't liked much by the migrator.
```
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'note' used in key specification without a key length (SQL: alter table `note` add index `idx_note`(`note`))
```

**Comment by arborrow** [comment]
Feel free to choose the one you think is best to keep. I trust you to resolve but if you have a specific question just let me know.
