### ISSUE TITLE
Relationship error

### ISSUE THREAD

**Issue by AtaGowani** [arborrow/montserrat#224]
## Description
Once the user is created. Showing the user yields to an error. This is due to the `620` assigned to the Montserrat relationship which does not exist locally. We need to figure out a way to maneuver around it.

## Screenshots
<img width="1440" alt="screen shot 2018-10-09 at 1 44 03 pm" src="https://user-images.githubusercontent.com/19475663/46691096-a90f0900-cbc9-11e8-9219-768995763356.png">

**Comment by arborrow** [comment]
I might suggest creating an environment variable for the name of the primary organization/company. Then we use that variable to seed an organization in the contact table. We could then create a get attribute on the contact model of company_id that would return the id of the retreat house where the environment variable matches the sort_name field (generally sort name is intended to be unique).

**Comment by arborrow** [comment]
I did create a SELF_CONTACT_ID variable. In addition, I created a seeder in commit 9017a832d994d4a2ee5f69ef7be6fa4b1123869d to create a contact for the organization (self). So I believe that we can consider this issue resolved.
