### ISSUE TITLE
Clean up public assets

### ISSUE THREAD

**Issue by AtaGowani** [arborrow/montserrat#227]
## Description
Clean up the css/js frontend assets to make frontend development less confusing.

**Comment by arborrow** [comment]
@AtaGowani after running npm run dev it seems to modify the images in public/images and creates a dist folder. I am wondering how best to handle this. Should we commit the images to the branch? I am presuming that they are being resized. Similarly with the dist folder is that something we want git to ignore? The challenge that it creates currently is that if I want do some work on a different branch I have to stash the changes and I would rather see it work well without having to commit or stash. Hopefully that makes some sense.

**Comment by arborrow** [comment]
I would like to see if we might begin introducing a bit of a color scheme. Something similar to production but it does not have to be identical. I trust your judgment from a UX perspective. I had started from: https://coolors.co/b7a99a-00204e-fbfbfb-bbb2a5-0d1321 and may have made some minor tweaks from there but if you have other ideas I am certainly open to suggestions. In terms of themes, I like the blues as they are representative of the dark blue waters of the lake, the tan representing the buildings, the light blue representing the sky. We could introduce some sunrise/sunset colors as well. In any case, I thought having this would give you a start on fine tuning the colors.

**Comment by AtaGowani** [comment]
Sounds great! I was thinking about getting into introducing colors as well. I'll be honest, I am not a huge fan of the tan but like your suggestions and reasons the other colors. I'll produce something and we can see how we like it.

**Comment by arborrow** [comment]
I am open to exploring other color schemes that you think would work well. We don't have to stick with the tan - it was just part of the Montserrat logo and buildings. The theme I see developing though is earthy, water, sky-like colors.

**Comment by arborrow** [comment]
So I was looking at: https://blog.visme.co/website-color-schemes/ just to get some ideas. Here are the ones that stood out to me as being in line with the earthy, blue-ish theme (in no particular order):

3 Natural and Earthy
7 Stylish and Sophisticated
22 Corporate and Traditional
30 Close to Nature
43 Eclectic and Peaceful
44 Classy and Traditional

Honorable mentions ;)
16 Sleek and Futuristic
19 Minimal Yet Warm
25 Vibrant and Elegant
37 Cheerful and Energetic
41 Intrepid and Fearless
42 Flat Design Colors
46 Corporate and Serious

Perhaps you might look through and see which ones you like and if might work toward something that works. Again, I don't want us to be limited by these - I just saw it and thought it would be a good starting point for further conversations on colors.
