### ISSUE TITLE
Automatic sending of pre-retreat confirmation emails not functioning

### ISSUE THREAD

**Issue by arborrow** [arborrow/montserrat#234]
Currently, Polanco is supposed to check if there are any Ignatian retreats that begin in the next 7 days and if so step through the list of registered participants and send them an email with a confirmation link for them to click on. Unfortunately, this does not seem to be working and there is no way to manually fire off the job. 

We need to troubleshoot why it is not working, enable a way to manually kick off the process, and after processing the list of retreatants send a summary email to registration@montserratretreat.org and cc: director@montserratretreat.org and the director of the retreat.

Subject: Pre-Retreat Confirmation Email Status Report

This status report is to update you of some automated communication with the participants for Retreat #{idnumber}-{title} ({start_date})

Successfully sent event/retreat confirmation email(s) to:
Failed to send event/retreat confirmation email(s) to: 
The following event/retreat participants did not have an email and should have a copy mailed to them (or called):

**Comment by arborrow** [comment]
So it looks like this is a classic duh issue ... Sadly, I broke this functionality. Maybe we should consider doing reviews ;) 

So you can start by reviewing:

https://github.com/arborrow/montserrat/commit/29225fda9fd60fad494a44727c3b9cfa1207ed0a#diff-7672f5a51d837c5488d5f0405024b8cc

In  app/Console/Commands/ConfirmationEmails.php I had changed from:
 `$primaryEmail = $retreatant->contact->primaryEmail()->first()->email;`

to:
`$primaryEmail = $retreatant->contact->primary_email_text; `

The problem is that there is no primary_email_text attribute in the Contact model. There is an email_primary_text which is what I had intended. 

That said, looking at the code in ConfirmationEmails.php I would like to rename the $retreatant variable to $registration since we are actually getting registrations and then using the retreatant relationship to get to the email (similarly to how we get the email address to display on the retreat.show blade). 

By using the same relationship and attribute to get the primary email address we will know that the ones being displayed on retreat.show in the registration table will be the ones that will be receiving the confirmation emails. 

Let me know if you have any questions about how to fix this up but it should be pretty trivial now.

**Comment by arborrow** [comment]
What is with all the space changes in https://github.com/arborrow/montserrat/commit/bcfe954e26d9c94e879b7ce7ff1c915f0b2e25ad ? By not including #234 in the git commit message it does not automatically show up here on github as part of the issue (not a big deal but I figured I would mention it). In any case, I have merged with wip-offering-dedup which is what I am currently using on production. There was a conflict with persons show blade although I am not sure what the difference was. I suspect I changed some things directly in production so I used whatever was there to overwrite anything from wip-234.

**Comment by AtaGowani** [comment]
I think the spaces are probably due to how my editor is configured. My defaults are 2 spaces, seems like the code base, however, has 4. I'll reconfigure my setting so we have consistency in spacing.

**Comment by AtaGowani** [comment]
@arborrow So the persons show blade was messing up due to spaces, correct? Or are there other conflicts too?

> What is with all the space changes in [bcfe954](https://github.com/arborrow/montserrat/commit/bcfe954e26d9c94e879b7ce7ff1c915f0b2e25ad) ? By not including #234 in the git commit message it does not automatically show up here on github as part of the issue (not a big deal but I figured I would mention it). In any case, I have merged with wip-offering-dedup which is what I am currently using on production. There was a conflict with persons show blade although I am not sure what the difference was. I suspect I changed some things directly in production so I used whatever was there to overwrite anything from wip-234.

**Comment by arborrow** [comment]
There were other conflicts but I didn't have time to explore and see
exactly what had changed so I would just stick with what is in the
wip-offering-dedup branch for the person view. I just wanted to bring your
attention to the spaces. Peace - Anthony
