### ISSUE TITLE
Donation: store or update can create false start and end dates

### ISSUE THREAD

**Issue by arborrow** [arborrow/montserrat#273]
Both on creation of and updating a donation, we need to be careful how the input is treated. The inputted data needs to be parsed by Carbon; however, a Carbon parse of null can return the current date/time. This is unintended. It would be better to use the request filled method to determine if there is a date provided - see  https://laravel.com/docs/5.6/requests#retrieving-input for a description

**Comment by AtaGowani** [comment]
Fixed in #274
